### ISSUE TITLE
Gracefully handle existing branches

### ISSUE THREAD

**Issue by ddymko** [GuillaumeFalourd/create-other-repo-branch-action#4]
Currently, if an existing branch exists, then it will end the run 

```sh
| Error: The branch name v0.0.2 is already used.
[Run/build]   ❌  Failure - Main Create new branch
[Run/build] exitcode '1': failure
[Run/build]   ❌  Failure - Main ddymko/create-other-repo-branch-action@updates3
[Run/build] exitcode '1': failure
```

It would be nice if we could add in a new input parameter that would allow a graceful exit so that our flow could continue.

The solution I am currently testing is as follows:

```sh
        if ${{ inputs.ignore_branch_exists }} && [ ! -z $(git branch --remotes --list 'origin/${{ inputs.new_branch_name }}') ]; then
            echo "[INFO] Branch ${{ inputs.new_branch_ref }} already exists. Skipping branch creation"
            exit 0
        fi
```        

The other option is to augment the existing branch check. I am happy to submit a PR with [what I have](https://github.com/ddymko/create-other-repo-branch-action/blob/ignore-existing-branch/action.yml) if you are open to the suggestion!

**Comment by GuillaumeFalourd** [comment]
Hi @ddymko , thank you for opening this issue!  👍🏼 

Your suggestion looks good to me, if you want to open a PR with this implementation, I'll generate a new tag version based on it and update the readme file with the new input (`ignore_branch_exists`) and add you to the contributors 🚀

**Comment by ddymko** [comment]
@GuillaumeFalourd Awesome! I'll submit a PR with my changes sometime today.
