### ISSUE TITLE
Feature: Allow use of deploy keys

### ISSUE THREAD

**Issue by ddymko** [GuillaumeFalourd/create-other-repo-branch-action#6]
Hey again 👋

I've really been enjoying your github action and have used it in combination with other actions.

One requirement that I currently have is I need to use SSH deploy keys instead of PAT. 

I have an implementation that I tested on a dummy repo which is working fine. 
Here are some links to those dummy repos:
- https://github.com/ddymko/repo-a/blob/v3.0.0-rc.3/.github/workflows/release.yml
- https://github.com/ddymko/repo-a/actions/runs/3193141290
- ~https://github.com/ddymko/repo-b/blob/rel/v3.0.0/version~ I realized I made this private in order to test the deploy key functionality

You can find my implementation here:
https://github.com/ddymko/create-other-repo-branch-action/blob/ssh-keys-deploy/action.yml#L31

I changed the conditional logic for cloning a bit. The flow is as 

- If `access_token` and `ssh_deploy_key` are defined: error
- if `access_token` is set: clone with access token
- if `ssh_deploy_key` is set: clone using ssh key
- if neither `acces_token` or `ssh_deploy_key` are set: do a basic clone

The other GHA I am using is https://github.com/cpina/github-action-push-to-another-repository which alraedy supports [SSH deploy keys](https://cpina.github.io/push-to-another-repository-docs/setup.html) which is where I borrowed some of the code to add support in for your action.

Let me know if this is something you are open to allowing for in your GHA!

**Comment by GuillaumeFalourd** [comment]
Hi @ddymko, thank you for coming back with another great suggestion! 🚀 

Your implementation looks great to me and it will definitely be a great addition 👍🏼 

Feel free to open a PR, I'll label it as `hacktoberfest` like the first one (don't know if you're participating, but you'll already be halfway the challenge) 😄

**Comment by ddymko** [comment]
Great to hear - I'll submit a PR then!

I wasn't taking part but I will now 😄
